### ISSUE TITLE
Multiple instances?

### ISSUE THREAD

**Issue by rolandomar** [ccadeptic23/Multi-Core-System-Monitor#3]
Hi,
Is it possible to have multiple instances?

Thanks,
Rolando

**Comment by ccadeptic23** [comment]
I'm fairly sure if u run the regression tests that happens.

**Comment by rolandomar** [comment]
Ok, I am trying to add a second applet to a different panel (cinnamon 2.5 with multiple monitors) without success. Probably it is a cinnamon issue.

**Comment by ccadeptic23** [comment]
Oops sry thought this was a different mailing list. I guess i have too many
lol.

Yeah that's a Cinnamon thing. Each applet is its own instance. Even if they
add it later, both monitors will share the configuration. so they will be
the same.

**Comment by rolandomar** [comment]
:) Do you know of any workaround?

**Comment by ccadeptic23** [comment]
Umm ive never done it but...i guess u can run different x sessions on eaxh
monitor each with a different Cinnamon instance...but again ive never tried
that....

Actually you can create a duplicate...copy and rename the applet folder to
a new name..change the applet name in the metadata file to tge same obe as
the new folder name...then cinnamon will see two different applets...the
original and new...this is probably the best option

**Comment by rolandomar** [comment]
worked:) Thanks for the help!
